version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"  
    volumes:
      - .:/var/www  
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: ASKNEAR
      POSTGRES_USER: Bouchta
      POSTGRES_PASSWORD: 0000
    ports:
      - "5432:5432" 
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_new
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - laravel
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/app
    working_dir: /app
    command: ["composer", "install"]

networks:
  laravel:

volumes:
  pgdata:
  pgadmin_data:
